### ISSUE TITLE
/charsetbodygroup for all users

### ISSUE THREAD

**Issue by KHishGit** [NebulousCloud/helix#110]
Im trying to make it so everyone can set their own bodygroups,  but not others. Also, the command is restricted to admin+ only and I need it to be available to all. Thanks for any help!

**Comment by impulsh** [comment]
`/CharSetBodygroup` is admin-only because you can set anyone else's bodygroup with that command, not just yours. You'll need to find a plugin that does this for you - check the `releases` channel in our discord.

As a side note, you can change the access level of commands with an admin mod that's CAMI-compliant (ulx, serverguard, etc)
