### ISSUE TITLE
Why 67 fonts in Helix?

### ISSUE THREAD

**Issue by mazer9** [NebulousCloud/helix#209]
Some of 67 fonts are not used. Why do you need such a large library of fonts?
e.x:
1. ixToolTipText
2. ixMonoSmallFont
3. ixToolTipText
4. ixSmallBoldFont
5. ... and more

Or, using just a couple of times:
1. ixItemBoldFont
2. ixIntroTitleFont
3. ixIntroTitleBlurFont
4. ixIntroSmallFont
5. ixItemDescFont
6. ixMinimalTitleFont
7. ... and more

Warnings from [surface.CreateFont:](https://wiki.facepunch.com/gmod/surface.CreateFont)
![image](https://user-images.githubusercontent.com/49285675/87945012-01d52c00-ca55-11ea-9c39-47f9e6df7879.png)

**Comment by DefenderVex** [comment]
It has not to create it more than once not create more than one at once. They all have different purposes and locations, One is intended as a big and large title font, another might be used in a small window you see when you hover over an inventory item. In other words, it gives design options instead of just blankly using the same font for everything.
